### ISSUE TITLE
Using different directories

### ISSUE THREAD

**Issue by freshyill** [tyrion/gridsome-plugin-netlify-cms-paths#1]
Do you know if there's something special in Gridsome about using the directories as specified in the [blog post](https://germano.dev/fix-netlify-cms-paths-on-gridsome/)? 

```yaml
media_folder: 'static/media'
public_folder: '/media'
```
This might be an obvious question, but Gridsome is still pretty light on the documentation unfortunately. I looked at the plugin and didn't see anything there.

I'd like to use `content/media` for my files, but it just refuses to work if I use something other than `static` as `media_folder` I try this. Thanks!

**Comment by tyrion** [comment]
Hello, 

Directories in gridsome have a well defined meaning, [as explained in the docs](https://gridsome.org/docs/directory-structure).
Placing your images inside `content` would be the logical choice, because Gridsome is able to find and optimize them. However, NetlifyCMS wouldn't be able to find them. This is why, as far as I know, the only solution to make both frameworks happy is to place them inside `static`.

Sorry for the late reply
